#ifndef WEBCONFIGURATIONTOOL_GLOBAL_H
#define WEBCONFIGURATIONTOOL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WEBCONFIGURATIONTOOL_LIB
# define WEBCONFIGURATIONTOOL_EXPORT Q_DECL_EXPORT
#else
# define WEBCONFIGURATIONTOOL_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBCONFIGURATIONTOOL_GLOBAL_H
