#define USER_MESSAGE 0x80000                            //用户自定义消息
#define MESSAGE_LANGUAGE_ZH USER_MESSAGE + 0xFFFF       //中文
#define MESSAGE_LANGUAGE_EN USER_MESSAGE + 0xFFFE       //英文
/*
#define OPENWEBEDIT USER_MESSAGE + 0x0001               //打开组态工具Web编辑器
#define OPENPICEDIT USER_MESSAGE + 0x0002               //打开组态工具Pic编辑器*/

#define OPENWEBEDIT USER_MESSAGE + 0x0028               //打开组态工具Web编辑器
#define OPENWEBFILEEDIT USER_MESSAGE + 0x0029           //打开组态工具Pic编辑器*/
#define OPENPICSTOREDIT USER_MESSAGE + 0x002A           //打开组态工具Web编辑器
#define OPENPICEDIT USER_MESSAGE + 0x002B               //打开组态工具Pic编辑器*/

//Web编辑器消息
#define ENABLEDRAG USER_MESSAGE + 0x0003                //打开窗体接受拖拽状态
#define DISABLEDRAG USER_MESSAGE + 0x0004               //关闭窗体接受拖拽状态
#define REFRESHTABPAGE USER_MESSAGE + 0x0005            //刷新tab页面
#define MESSAGESAVEWEBFILE USER_MESSAGE + 0x000E        //保存WEB页面
#define WEBEDITPAGEENABLE USER_MESSAGE + 0x000F         //只有在编辑网页的窗口下，网页编辑工具栏上的按钮处于可点击状态
#define WEBMESSAGE_SELECTEALL USER_MESSAGE + 0x0010     //全选消息
#define WEBMESSAGE_COPY USER_MESSAGE + 0x0011			//复制消息
#define WEBMESSAGE_PASTE USER_MESSAGE + 0x0012			//粘贴消息
#define WEBMESSAGE_DELETE USER_MESSAGE + 0x0013			//删除消息
#define WEBMESSAGE_UNDO USER_MESSAGE + 0x0014			//撤销消息
#define WEBMESSAGE_REDO USER_MESSAGE + 0x0015			//重做消息
#define WEBMESSAGE_ALIGNTOP USER_MESSAGE + 0x0016		//上对齐消息
#define WEBMESSAGE_ALIGNBOTTOM USER_MESSAGE + 0x0017	//下对齐消息
#define WEBMESSAGE_ALIGNLEFT USER_MESSAGE + 0x0018		//左对齐消息
#define WEBMESSAGE_ALIGNRIGHT USER_MESSAGE + 0x0019		//右对齐消息
#define WEBMESSAGE_ALIGNHORIZONTAL USER_MESSAGE + 0x001A//水平对齐消息
#define WEBMESSAGE_ALIGNVERTICAL USER_MESSAGE + 0x001B	//垂直对齐消息
#define WEBMESSAGE_EQUHORIZONTAL USER_MESSAGE + 0x001C	//水平等间距消息
#define WEBMESSAGE_EQUVERTICAL USER_MESSAGE + 0x001D	//垂直等间距消息
#define WEBMESSAGE_SAMEWIDTH USER_MESSAGE + 0x001E		//等宽消息
#define WEBMESSAGE_SAMEHEIGHT USER_MESSAGE + 0x001F		//等高消息
#define WEBMESSAGE_SAMESIZE USER_MESSAGE + 0x0020		//等大小消息
#define WEBMESSAGE_SETWEBTITLE USER_MESSAGE + 0x0021	//设置网页标题栏消息
#define WEBMESSAGE_SETWEBSIZE USER_MESSAGE + 0x0022		//设置网页大小消息
#define WEBMESSAGE_SETUNDOENABLE USER_MESSAGE + 0x0023	//设置撤销按钮灰化状态
#define WEBMESSAGE_SETREDOENABLE USER_MESSAGE + 0x0024	//设置重做按钮灰化状态
#define WEBMESSAGE_ZOOMNORMAL USER_MESSAGE + 0x0025		//正常大小
#define WEBMESSAGE_ZOOMIN USER_MESSAGE + 0x0026			//放大
#define WEBMESSAGE_ZOOMOUT USER_MESSAGE + 0x0027		//缩小

#define  WEBMESSAGE_SENDSVGPATH USER_MESSAGE + 0X0028  //发送svg路径给前端


//图片编辑器消息
#define MESSAGE_DRAW_SELECT    USER_MESSAGE + 0x0006    //绘画工具选择
#define MESSAGE_DRAW_LINE      USER_MESSAGE + 0x0007    //绘画工具选择
#define MESSAGE_DRAW_RECTANGLE USER_MESSAGE + 0x0008    //绘画工具选择
#define MESSAGE_DRAW_ELLIPSE   USER_MESSAGE + 0x0009    //绘画工具选择
#define MESSAGE_DRAW_ROURECT   USER_MESSAGE + 0x000a    //绘画工具选择
#define MESSAGE_DRAW_POLYGON   USER_MESSAGE + 0x000b    //绘画工具选择
#define MESSAGE_DRAW_TEXT      USER_MESSAGE + 0x000c    //绘画工具选择
#define MESSAGE_DRAW_PICTURE   USER_MESSAGE + 0x000d    //绘画工具选择

//
#define PROJECT_CURRENT_PAGE     USER_MESSAGE + 0x0040   
#define WEBMESSAGE_GETIMAGEPATH  USER_MESSAGE + 0X0041
#define WEBMESSAGE_PROJECT_PATH  USER_MESSAGE + 0X0042
#define IMAGEPATH_TO_PROJECT     USER_MESSAGE + 0X0043
#define  SAVE_AS_HTML            USER_MESSAGE + 0X0044

